name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]  # here must have a space between on: and [ !!


jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:

      - uses: actions/checkout@v3  # This is necessary for the tj-actions/changed...Otherwise that function won't work. Because this step is to pull the code and enter the code.
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          

      - name: Traverse all files
        run: |
          dir=`ls ${PWD}/examples` 
            for i in $dir
              do
                  echo ${i}
              done

#          abs=`pwd`
#          echo "${abs} aaa"