name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]  # here must have a space between on: and [ !!


jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          

      - name: Traverse all files
        run: |
          dir="/examples/"
          ls $dir | while read line
          do
              file=${dir}${line}
              echo file
          done